#include "lifi_plugin.h"

// Need more information about the interface for plugins? Please read the README.md!

// You can check LI.FI swap methods here
// https://louper.dev/diamond/0x362fA9D0bCa5D19f743Db50738345ce2b40eC99f?network=mainnet
//
// swapTokensGeneric 0x4630a0d8
static const uint8_t LIFI_SWAP_TOKENS_GENERIC_SELECTOR[SELECTOR_SIZE] = {0x46, 0x30, 0xa0, 0xd8};

// startBridgeTokenViaNXTP 0xc9fb76b1
static const uint8_t LIFI_START_BRIDGE_TOKEN_VIA_NXTP_SELECTOR[SELECTOR_SIZE] = {0xc9,
                                                                                 0xfb,
                                                                                 0x76,
                                                                                 0xb1};

// Array of all the different LI.FI selectors.
const uint8_t *const LIFI_SELECTORS[NUM_LIFI_SELECTORS] = {
    LIFI_SWAP_TOKENS_GENERIC_SELECTOR,
    LIFI_START_BRIDGE_TOKEN_VIA_NXTP_SELECTOR,
};

// Used to indicate that the beneficiary should be the sender.
const uint8_t NULL_ETH_ADDRESS[ADDRESS_LENGTH] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                                  0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

const uint8_t NULL_CHAIN_ID[INT_64_LENGTH] = {0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00,
                                              0x00};

const ledger_network_info_t LEDGER_SUPPORTED_NETWORK[NUM_LEDGER_SUPPORTED_NETWORK] = {
    {"ETH", "Ethereum"},
    {"BNB", "BSC"},
    {"MATIC", "Polygon"},
};

const lifi_network_info_t LIFI_NETWORK_MAPPING[NUM_LIFI_NETWORKS] = {{{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x01},  // 1
                                                                      "Ethereum"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x0a},  // 10
                                                                      "Optimism"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x38},  // 56
                                                                      "BSC"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x42},  // 66
                                                                      "OKEX"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x64},  // 100
                                                                      "Gnosis"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x7a},  // 122
                                                                      "Fuse"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x89},  // 137
                                                                      "Polygon"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0xfa},  // 250
                                                                      "Fantom"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x05,
                                                                       0x04},  // 1284
                                                                      "Moonbeam"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x05,
                                                                       0x05},  // 1285
                                                                      "Moonriver"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0xa4,
                                                                       0xb1},  // 42161
                                                                      "Arbitrum"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0xa4,
                                                                       0xec},  // 42220
                                                                      "Celo"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0xa8,
                                                                       0x6a},  // 43114
                                                                      "Avalanche"},
                                                                     {{0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x00,
                                                                       0x63,
                                                                       0x56,
                                                                       0x4c,
                                                                       0x40},  // 1666600000
                                                                      "Harmony"}};